done
mate-academy/js_tree-from-object-DOM pull request #188
Opened 2020-10-05 14:53 UTC by aionova

- [DEMO LINK](https://aionova.github.io/js_tree-from-object-DOM/)

2020-10-05 19:18 UTC, yazheviks approved these changes
Круто!

2020-10-07 15:12 UTC, solaryasha requested changes
У корневого списку немає тега `ul`
<img width="385" alt="Screenshot 2020-10-07 at 18 10 58" src="https://user-images.githubusercontent.com/32794096/95350131-830bc480-08c8-11eb-9d80-7ffa9d1e9519.png">

2020-10-08 13:48 UTC, solaryasha requested changes

2020-10-08 13:48 UTC, solaryasha commented on src/scripts/main.js
> +      const listInList = document.createElement('li');
Винеси з `if else` інструкції , ти повторюєш його двічі

2020-10-08 16:28 UTC, solaryasha approved these changes
🔥

2023-09-27 09:09 UTC, closed without merging