Develop
mate-academy/js_tree-from-object-DOM pull request #194
Opened 2020-10-08 15:20 UTC by AndriiManyak

[DEMO LINK](https://AndriiManyak.github.io/<repo_name>/)

2020-10-08 18:11 UTC, achervona approved these changes
Cool!

2020-10-09 07:12 UTC, solaryasha requested changes

2020-10-09 07:12 UTC, solaryasha commented on src/scripts/main.js
> +  const uList = document.createElement('ul');
Не скорочуй назви змінних

2020-10-09 07:21 UTC, solaryasha approved these changes

2026-02-12 23:02 UTC, closed without merging