solution
mate-academy/js_tree-from-object-DOM pull request #289
Opened 2021-03-08 16:05 UTC by yashnyi

[DEMO LINK](https://yashnyi.github.io/js_tree-from-object-DOM/)

2021-03-08 21:18 UTC, artur-shpontak approved these changes
https://i.gifer.com/origin/d8/d8c8cf6100d3889178f16d1ea03972f0.gif

2021-03-09 13:37 UTC, solaryasha requested changes

2021-03-09 13:37 UTC, solaryasha commented on src/scripts/main.js
> +    if (data[key].length !== 0) {
Це ж не масив, потрібна перевірка на наявність ключів

2021-03-09 14:34 UTC, solaryasha approved these changes

2025-09-01 20:49 UTC, closed without merging